name: Echo Tests1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello on dew-large runner
        run: |
          echo "Hello World!"
