name: Build local nnd image and push it to ecr
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Say Hello and print runner infp
        run: |
          echo "Hello World!"
          hostnamectl
