name: Build and publish local_db docker image.
on:
  workflow_dispatch:
  push:
      branches:
      - 'add_build_yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
